/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentRPSystem;

import StudentRPSystem.db.AdminAcc;
import StudentRPSystem.db.StudentAcc;
import StudentRPSystem.ui.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author rasel
 */
public class Holder extends javax.swing.JFrame {

    /**
     * Creates new form Holder
     */
    public Holder() {
        initComponents();
        adminMenu.setVisible(false);
        studentMenu.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtfirstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtlastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtConPass = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        menuItemAdminSign = new javax.swing.JMenuItem();
        menuItemStudentSign = new javax.swing.JMenuItem();
        menuItemLogin = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();
        adminMenu = new javax.swing.JMenu();
        menuItemMarksCollection = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        markSheet1st = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        studentMenu = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Login", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Matura MT Script Capitals", 0, 24))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        jLabel1.setText("First name:");

        txtfirstName.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        txtfirstName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        jLabel2.setText("Last name:");

        txtlastName.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        txtlastName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        jLabel5.setText("Password:");

        txtPass.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        txtPass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        jLabel6.setText("Confirm password:");

        txtConPass.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        txtConPass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        loginButton.setBackground(new java.awt.Color(255, 255, 255));
        loginButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        jLabel4.setText("Uset type:");

        cmbType.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        cmbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Select user type---", "Admin", "Student", " " }));
        cmbType.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtlastName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtfirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtConPass, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtlastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(154, 154, 154))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtConPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(loginButton)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jMenu4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jMenu4.setText("User");
        jMenu4.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N

        menuItemAdminSign.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        menuItemAdminSign.setText("Sign up as Admin");
        menuItemAdminSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAdminSignActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemAdminSign);

        menuItemStudentSign.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        menuItemStudentSign.setText("Sign up as Student");
        menuItemStudentSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemStudentSignActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemStudentSign);

        menuItemLogin.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        menuItemLogin.setText("Login");
        menuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLoginActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemLogin);

        menuLogout.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        menuLogout.setText("Log out");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenu4.add(menuLogout);

        jMenuBar1.add(jMenu4);

        adminMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        adminMenu.setText("Admin Activity");
        adminMenu.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N

        menuItemMarksCollection.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        menuItemMarksCollection.setText("Record Marks");
        menuItemMarksCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMarksCollectionActionPerformed(evt);
            }
        });
        adminMenu.add(menuItemMarksCollection);

        jMenu1.setText("Result sheet");
        jMenu1.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N

        markSheet1st.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        markSheet1st.setText("1st Semester");
        markSheet1st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markSheet1stActionPerformed(evt);
            }
        });
        jMenu1.add(markSheet1st);

        jMenuItem3.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        jMenuItem3.setText("2nd Semester");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        jMenuItem4.setText("3rd Semester");
        jMenu1.add(jMenuItem4);

        jMenuItem7.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        jMenuItem7.setText("4th Semester");
        jMenu1.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        jMenuItem8.setText("5th Semester");
        jMenu1.add(jMenuItem8);

        jMenuItem1.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        jMenuItem1.setText("6th Semester");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        jMenuItem2.setText("7th Senester");
        jMenu1.add(jMenuItem2);

        jMenuItem9.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        jMenuItem9.setText("8th Semester");
        jMenu1.add(jMenuItem9);

        adminMenu.add(jMenu1);

        jMenu5.setText("Marksheet");
        jMenu5.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N

        jMenuItem12.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        jMenuItem12.setText("1st Semester");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        adminMenu.add(jMenu5);

        jMenuBar1.add(adminMenu);

        studentMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        studentMenu.setText("Student Activity");
        studentMenu.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N

        jMenu2.setText("Result sheet");
        jMenu2.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        jMenuItem5.setText("1st semester");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        jMenuItem6.setText("2nd semester");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        studentMenu.add(jMenu2);

        jMenu3.setText("Marksheet");
        jMenu3.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N

        jMenuItem10.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        jMenuItem10.setText("1st semester");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        jMenuItem11.setText("2nd semester");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        studentMenu.add(jMenu3);

        jMenuBar1.add(studentMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean checkValidation() {
        if (!txtfirstName.getText().trim().isEmpty()) {
            if (!txtlastName.getText().trim().isEmpty()) {
                if (cmbType.getSelectedIndex() != 0) {
                    if (!txtPass.getText().trim().isEmpty()) {
                        if (!txtConPass.getText().trim().isEmpty()) {
                            return true;
                        } else {
                            JOptionPane.showMessageDialog(null, "Please confirm password.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Please enter the password.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please select user type.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please enter last name.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter first name.");
        }
        return false;
    }

    public void txtClear() {
        txtfirstName.setText("");
        txtlastName.setText("");
        txtPass.setText("");
        txtConPass.setText("");

    }

    private void menuItemMarksCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMarksCollectionActionPerformed
        // TODO add your handling code here:
      /*
         * if (cmbType.getSelectedIndex() != 1) {
         * JOptionPane.showMessageDialog(null, "Required an Admin to access
         * this!"); } else {
         */
        MarksCount markCount = new MarksCount();
        jScrollPane1.getViewport().add(markCount);
        //}
    }//GEN-LAST:event_menuItemMarksCollectionActionPerformed

    private void menuItemAdminSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAdminSignActionPerformed

        if (cmbType.getSelectedIndex() == 0) {
            SignUpAsAdmin admin = new SignUpAsAdmin();
            jScrollPane1.getViewport().add(admin);
        } else {
            JOptionPane.showMessageDialog(null, "Log out first!");
        }
    }//GEN-LAST:event_menuItemAdminSignActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        if (cmbType.getSelectedIndex() == 1) {
            try {
                if (checkValidation()) {
                    AdminAcc admin = new AdminAcc();
                    admin.setFirstName(this.txtfirstName.getText());
                    admin.setLastName(this.txtlastName.getText());
                    admin.setChoosePass(this.txtPass.getText());
                    admin.setPassword(this.txtConPass.getText());
                    if (txtPass.getText().equalsIgnoreCase(txtConPass.getText())) {
                        boolean auth = admin.findAdmin();
                        if (auth) {
                            txtClear();

                            JOptionPane.showMessageDialog(null, "Logged in as admin successfully.");
                            adminMenu.setVisible(true);
                            studentMenu.setVisible(true);
                            WelcomePanel welcome = new WelcomePanel();
                            jScrollPane1.getViewport().add(welcome);

                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Incorrect password or password doesn't matched!");
                    }

                }
            } catch (ClassNotFoundException ex) {
                ex.printStackTrace();

            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        } else {

            if (cmbType.getSelectedIndex() == 2) {
                try {
                    if (checkValidation()) {
                        StudentAcc student = new StudentAcc();
                        student.setFirstname(this.txtfirstName.getText());
                        student.setLastname(this.txtlastName.getText());
                        student.setPass(this.txtPass.getText());
                        student.setConPass(this.txtConPass.getText());

                        if (txtPass.getText().equalsIgnoreCase(txtConPass.getText())) {
                            boolean auth = student.findStudent();
                            if (auth) {
                                txtClear();

                                JOptionPane.showMessageDialog(null, "Logged as student successfully.");
                                studentMenu.setVisible(true);
                                WelcomePanel welcome = new WelcomePanel();
                                jScrollPane1.getViewport().add(welcome);
                                adminMenu.setVisible(false);

                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Incorrect password or password doesn't matched!");
                        }

                    }
                } catch (ClassNotFoundException ex) {
                    ex.printStackTrace();

                } catch (SQLException ex) {
                    ex.printStackTrace();
                }

            } else {
                JOptionPane.showMessageDialog(null, "Invalid Account!");
                txtClear();
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void menuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLoginActionPerformed

        if (cmbType.getSelectedIndex() == 0) {
            jScrollPane1.getViewport().add(jPanel1);
        } else {
            JOptionPane.showMessageDialog(null, "Log out first!");
        }
    }//GEN-LAST:event_menuItemLoginActionPerformed

    private void menuItemStudentSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemStudentSignActionPerformed

        if (cmbType.getSelectedIndex() == 0) {
            SignUpAsStudent student = new SignUpAsStudent();
            jScrollPane1.getViewport().add(student);
        } else {
            JOptionPane.showMessageDialog(null, "Log out first!");
        }
    }//GEN-LAST:event_menuItemStudentSignActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed

        if (cmbType.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Doesn't logged in yet!");
        } else {
            JOptionPane.showMessageDialog(null, "Are you sure to log out?");
            jScrollPane1.getViewport().add(jPanel1);
            txtClear();
            cmbType.setSelectedIndex(0);
            adminMenu.setVisible(false);
            studentMenu.setVisible(false);
        }
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void markSheet1stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markSheet1stActionPerformed

        Marksheet1st obj = new Marksheet1st();
        jScrollPane1.getViewport().add(obj);
    }//GEN-LAST:event_markSheet1stActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
         Marksheet2nd obj = new Marksheet2nd();
        jScrollPane1.getViewport().add(obj);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed

        DisplayResult1st obj = new DisplayResult1st();
        jScrollPane1.getViewport().add(obj);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed

        DisplayResult1st obj = new DisplayResult1st();
        jScrollPane1.getViewport().add(obj);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        Marksheet1st obj = new Marksheet1st();
        jScrollPane1.getViewport().add(obj);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

           Marksheet2nd obj = new Marksheet2nd();
        jScrollPane1.getViewport().add(obj);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed

        
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Holder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Holder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Holder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Holder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Holder().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu adminMenu;
    private javax.swing.JComboBox cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JMenuItem markSheet1st;
    private javax.swing.JMenuItem menuItemAdminSign;
    private javax.swing.JMenuItem menuItemLogin;
    private javax.swing.JMenuItem menuItemMarksCollection;
    private javax.swing.JMenuItem menuItemStudentSign;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenu studentMenu;
    private javax.swing.JPasswordField txtConPass;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtfirstName;
    private javax.swing.JTextField txtlastName;
    // End of variables declaration//GEN-END:variables
}
